import streamlit as st

st.title("Mulheres e Jogos")

st.markdown("Em 2025, a **Pesquisa Game Brasil** revelou que as mulheres são a maioria entre os jogadores de jogos digitais, representando **53,2%** do público. Entretanto, mesmo sendo maioria, elas ainda encontram diversas dificuldades para entrar e permanecer no universo dos jogos eletrônicos devido ao machismo presente na cultura gamer.")
st.markdown("Os jogos eletrônicos são frequentemente associados à figura masculina, e a indústria continua, em grande parte, produzindo conteúdos voltados prioritariamente para esse público. Como consequência, a falta de representatividade feminina nos personagens acaba afastando muitas jogadoras. Além de a presença feminina ser menor, quando existe, ela costuma ser marcada pela hipersexualização e pela objetificação, com personagens criadas para agradar ao olhar masculino, reforçando estereótipos e limitando a identificação das mulheres com os jogos.")
st.markdown("Outro fator relevante que afasta as mulheres desse ambiente é a agressão e o assédio sexual constantes. Comentários que questionam a capacidade feminina de jogar, ofensas verbais e até menções a estupro são recorrentes. Nessas situações, as mulheres são desqualificadas como jogadoras e reduzidas a objetos de desejo ou de ódio, o que evidencia a violência simbólica e psicológica presente nas interações online.")
st.markdown("Para evitar essas situações, muitas mulheres optam por utilizar nicknames masculinos ou neutros, escondendo sua identidade de gênero para não serem alvo de ataques. Dessa forma, deixam de ser reconhecidas como mulheres para que possam simplesmente jogar em paz, o que demonstra o quanto o ambiente ainda é hostil e excludente.")
st.markdown("Essa exclusão também se manifesta nas esferas competitivas e profissionais dos jogos eletrônicos. Mulheres são minoria em campeonatos, equipes profissionais, desenvolvimento de jogos e produção de conteúdo gamer, enfrentando frequentemente o descrédito em relação às suas habilidades. Mesmo quando alcançam bons resultados, seu desempenho tende a ser questionado, enquanto jogadores homens são automaticamente reconhecidos como competentes. Esse cenário gera um ciclo de invisibilidade, desmotivação e afastamento.")
st.markdown("Todos esses fatores contribuem para a manutenção do estereótipo feminino de inferioridade em relação aos homens, reforçando a ideia de que as mulheres precisam constantemente se provar para frequentar ambientes historicamente masculinizados. Assim, apesar de sua expressiva presença no público gamer, o machismo estrutural impede que os jogos eletrônicos sejam, de fato, um espaço igualitário, seguro e inclusivo.")
st.markdown("Apesar de todos esses problemas, o cenário dos jogos eletrônicos está mudando aos poucos. Cada vez mais mulheres estão ocupando espaço na indústria, seja como jogadoras, desenvolvedoras, criadoras de conteúdo, streamers ou atletas de e-sports. Essa presença crescente ajuda a trazer personagens mais diversos, histórias mais realistas e experiências de jogo que dialogam melhor com diferentes públicos. Além disso, o debate sobre machismo e representatividade tem ganhado mais força, fazendo com que empresas e comunidades passem a repensar atitudes e comportamentos. " \
"Mesmo que ainda existam desafios, essas mudanças mostram que o universo gamer está caminhando para se tornar um espaço mais justo, diverso e acolhedor para todos.")